### ISSUE TITLE
Throwing Error: options.uri is a required argument

### ISSUE THREAD

**Issue by bedeoverend** [feathersjs/feathers-sendgrid#3]
Everytime I try send an email, I'm getting `Error: options.uri is a required argument`. Even if I simplify it down to it's most basic use case I can't seem to get rid of it. See the full stack trace below.

Also, I've moved over to feathers-mailer for now, so if this is just an edge case then it's not a stress for me - just thought I'd post incase others have the same issue.

```
error:  Error: options.uri is a required argument
    at Request.init (/Users/Bede/Development/feathers-api/node_modules/feathers-sendgrid/node_modules/request/request.js:245:31)
    at new Request (/Users/Bede/Development/feathers-api/node_modules/feathers-sendgrid/node_modules/request/request.js:141:8)
    at request (/Users/Bede/Development/feathers-api/node_modules/feathers-sendgrid/node_modules/request/index.js:55:10)
    at Object._send (/Users/Bede/Development/feathers-api/node_modules/feathers-sendgrid/node_modules/sendgrid/lib/sendgrid.js:72:15)
    at Object.send [as _send] (/Users/Bede/Development/feathers-api/node_modules/feathers-sendgrid/node_modules/sendgrid/lib/sendgrid.js:54:21)
    at /Users/Bede/Development/feathers-api/node_modules/feathers-sendgrid/lib/index.js:53:15
    at new Promise (/Users/Bede/Development/feathers-api/node_modules/core-js/modules/es6.promise.js:197:7)
    at Object.create (/Users/Bede/Development/feathers-api/node_modules/feathers-sendgrid/lib/index.js:49:14)
    at Object.wrapper (/Users/Bede/Development/feathers-api/node_modules/feathers/lib/mixins/promise.js:6:28)
    at Object.<anonymous> (/Users/Bede/Development/feathers-api/node_modules/uberproto/lib/proto.js:30:17)
```

**Comment by ekryski** [comment]
@bedeoverend thanks for reporting! We'll take a look a little later this week.

**Comment by corymsmith** [comment]
@bedeoverend I'll get this sorted this week as @ekryski mentioned

**Comment by bedeoverend** [comment]
@corymsmith @ekryski :+1: thanks guys!

**Comment by corymsmith** [comment]
Spent a bit of time digging into this, looks like a Sendgrid issue though I'm not sure why they haven't accepted that PR.

**Comment by ekryski** [comment]
This is now fixed after upgrading to Sendgrid V3 API with module version v0.2.0
